version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/Product_app
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network
  
volumes:
  mongo-data:
networks:
  app-network:
    name: app-network
