version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - python

  python:
    image: python:3.11
    volumes:
      - ./server:/app
    working_dir: /app
    command: python app.py
    environment:
      - PYTHONUNBUFFERED=1
